<?php

return [
    'boss'=>[
        'dashboard',
        'statistics',
        'order',
        'promotion',
        'user',
        'product',
        'product_category',
        'post',
        'post_category',
        'branch'
    ],
    'admin'=>[
        'user',
        'product',
        'product_category',
        'post',
        'post_category',
        'branch'
    ],
    [
        'dashboard',
        'statistics',
        'order',
        'promotion'
    ]
];